### ISSUE TITLE
Support inclusion-based filtering with wildcard for specific container and namespace names

### ISSUE THREAD

**Issue by btungut** [btungut/fluentd-kube-elastic#2]
Currently, the system supports ignoring specific container or namespace names, which is useful to exclude known unimportant workloads. However, there is no way to do the opposite — to explicitly include only certain containers or namespaces (using patterns or wildcards), while ignoring everything else by default.

Example:
```
inclusion:
  namespacePatterns:
    - "prod-*"
    - "team-a*"
  containerPatterns:
    - "api-*"
    - "worker-*"
```
